<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Exe</OutputType>
	<TargetFramework>net8.0-windows</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<SelfContained>true</SelfContained>
	<PublishSingleFile>true</PublishSingleFile>
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	<UseWindowsForms>true</UseWindowsForms>
	<DockerfileContext>.</DockerfileContext>
	<StartupObject>vulnVM</StartupObject>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
	<PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
	<Compile Remove="vulnVMAgent\**\*.cs" />
  </ItemGroup>

	<Target Name="BuildAndCopyAgent" AfterTargets="Build">
		<Exec Command="dotnet publish &quot;$(MSBuildProjectDirectory)\vulnVMAgent\vulnVMAgent.csproj&quot; -c $(Configuration) -o &quot;$(MSBuildProjectDirectory)\obj\agent-publish&quot;" />
		<Copy SourceFiles="$(MSBuildProjectDirectory)\obj\agent-publish\vulnVMAgent.exe" DestinationFolder="$(OutDir)" />
	</Target>

</Project>
